### PR TITLE
fix: Restore init_resample_midthickness_wf for backwards compatibility

### PR DESCRIPTION
**Pull request by effigies**
Sorry @mgxd. Try out this branch?

### CODE REVIEW

**Comment by mgxd** [comment]
@effigies I'm fine with using https://github.com/nipreps/smriprep/tree/dev-nibabies for the time being - will shift back to `master` shortly after a nibabies release

**Comment by effigies** [comment]
@mgxd The plan is just to pin to a dev branch, or do you need a release without that change in? If you're pushing to pypi, you'll presumably need a PyPI release.

**Comment by mgxd** [comment]
i just pushed an [alpha to docker hub](https://hub.docker.com/layers/nipreps/nibabies/25.0.0a1/images/sha256-322bdacc63101b3a97b470f0f4bc20f710995fc610c09d3cd34c1256a66e1cd2) to get hbcd processing underway - plan is to sync up before the 25.0.0 release

**Comment by effigies** [comment]
Got it.

**Pull request closed without merging**
