### PR TITLE
MAINT: CircleCI housekeeping

### PR DESCRIPTION
**Pull request by mgxd**
Following what was implemented in fmriprep:

- Add Docker orb for easy authentication
- Bump machine images to latest LTS (focal)
- Remove setfacl calls

### CODE REVIEW

**Comment by mgxd** [comment]
I'm planning on following fMRIPrep's implementation and switching over to RTD - currently the build is hitting a memory issue (https://readthedocs.org/projects/smriprep/builds/14435765/), I've reached out to RTD support about expanding the build resources.

**Comment by effigies** [comment]
Our docs are set up to be on GH pages, not RTD.

**Comment by mgxd** [comment]
> It re-builds all previous releases each time.

What is the advantage of this? It seems to me RTD would significantly reduce the amount of code we'd have to maintain

**Comment by effigies** [comment]
I think Oscar has mentioned a kind of perennial threat of RTD limiting the free builds in some way.

The rebuild every time is a bug, btw.

**Comment by mgxd** [comment]
Okay, I'm still not 100% convinced (maybe @oesteban can chime in) but for the sake of getting a release out I'll proceed with the current implementation

**Pull request merged**
